crm/urls.py
from django.conf.urls import url
from . import views
from django.urls import path, re_path

app_name = 'crm'
urlpatterns = [
    path('', views.home, name='home'),
    re_path(r'^home/$', views.home, name='home'),
    path('volunteer_list', views.volunteer_list, name='volunteer_list'),
    path('volunteer/<int:pk>/edit/', views.volunteer_edit, name='volunteer_edit'),
    path('volunteer/<int:pk>/delete/', views.volunteer_delete, name='volunteer_delete'),
    path('availability_list', views.availability_list, name='availability_list'),
    path('availability/create/', views.availability_new, name='availability_new'),
    path('availability/<int:pk>/edit/', views.availability_edit, name='availability_edit'),
    path('availability/<int:pk>/delete/', views.availability_delete, name='availability_delete'),
    path('opportunity_list', views.opportunity_list, name='opportunity_list'),
    path('opportunity/create/', views.opportunity_new, name='opportunity_new'),
    path('opportunity/<int:pk>/edit/', views.opportunity_edit, name='opportunity_edit'),
    path('opportunity/<int:pk>/delete/', views.opportunity_delete, name='opportunity_delete'),
    path('assignment_list', views.assignment_list, name='assignment_list'),
    path('assignment/create/', views.assignment_new, name='assignment_new'),
    path('assignment/<int:pk>/edit/', views.assignment_edit, name='assignment_edit'),
    path('assignment/<int:pk>/delete/', views.assignment_delete, name='assignment_delete'),
    path('organization_list', views.organization_list, name='organization_list'),
    path('organization/create/', views.organization_new, name='organization_new'),
    path('organization/<int:pk>/edit/', views.organization_edit, name='organization_edit'),
    path('organization/<int:pk>/delete/', views.organization_delete, name='organization_delete'),
    # path('volunteer/<int:pk>/summary/', views.summary, name='summary'),
]

mfscrm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, include
from django.urls import path, re_path
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crm.urls')),
    path('accounts/password_change/',
        PasswordChangeView.as_view(template_name='registration/passwordchangeform.html'),
        name='passwordchangeform'),
    path('accounts/password_change/done',
        PasswordChangeDoneView.as_view(template_name='registration/passwordchangedone.html'),
        name='password_change_done'),
    path('accounts/password_reset/',
        PasswordResetView.as_view(template_name='registration/passwordresetform.html'),
        name='passwordresetform'),
    path('accounts/password_reset/done',
        PasswordResetDoneView.as_view(template_name='registration/passwordresetdone.html'),
        name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(template_name='registration/passwordresetconfirm.html'),
        name='password_reset_confirm'),
    path('accounts/password_reset/complete',
        PasswordResetCompleteView.as_view(template_name='registration/passwordresetcomplete.html'),
        name='password_reset_complete'),
    re_path(r'^accounts/login/$', LoginView.as_view(template_name='registration/login.html'), name="login"),
    re_path(r'^accounts/logout/$', LogoutView.as_view(), LogoutView.next_page, name="logout"),

]

crm/forms.py
from django import forms
from .models import Volunteer
from .models import Volunteer, Availability, Opportunity, Assignment, Organization

class VolunteerForm(forms.ModelForm):
    class Meta:
        model = Volunteer
        fields = ('user', 'email', 'address', 'city', 'state', 'zipcode', 'phone_number')

class AvailabilityForm(forms.ModelForm):
   class Meta:
       model = Availability
       fields = ('service_category', 'description', 'location', 'setup_time', 'cleanup_time' )
       exclude = ('vol_name',)

class OpportunityForm(forms.ModelForm):
   class Meta:
       model = Opportunity
       fields = ('organization', 'date', 'time')

class AssignmentForm(forms.ModelForm):
   class Meta:
       model = Assignment
       fields = ('volunteer', 'opportunity') 

class OrganizationForm(forms.ModelForm):
   class Meta:
       model = Organization
       fields = ('name', 'street', 'city', 'state', 'zip', 'phone')

crm/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.views import PasswordResetView
from django.shortcuts import render
from .models import *
from .forms import *
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.db.models import Sum



now = timezone.now()
def home(request):
   return render(request, 'crm/home.html',
                 {'crm': home})

# def rolemanagercheck(user):
	# if user.groups == ('Manager'):
		# return True
	# else:
		# return False

def rolemanagercheck(user):
	return user.groups.filter(name__in=['Managers'])
	
def rolevolunteercheck(user):
	return user.groups.filter(name__in=['Volunteer'])

# def rolevolunteercheck(self):
	# if self.groups == ('Volunteer'):
		# return True
	# else:
		# return False
		

@login_required
# @user_passes_test(rolecheck)
def assignment_list(request):
    assignments = Assignment.objects.filter(created_date__lte=timezone.now())
    return render(request, 'crm/assignment_list.html',
                 {'assignments': assignments})

@login_required
# @user_passes_test(rolevolunteercheck)
def assignment_new(request):
   if request.method == "POST":
       form = AssignmentForm(request.POST)
       if form.is_valid():
           assignment = form.save(commit=False)
           assignment.created_date = timezone.now()
           assignment.save()
           assignments = Assignment.objects.filter(created_date__lte=timezone.now())
           return render(request, 'crm/assignment_list.html',
                         {'assignments': assignments})
   else:
       form = AssignmentForm()
       # print("Else")
   return render(request, 'crm/assignment_new.html', {'form': form})

@login_required
# @user_passes_test(rolevolunteercheck)
def assignment_edit(request, pk):
   assignment = get_object_or_404(Assignment, pk=pk)
   if request.method == "POST":
       # update
       form = AssignmentForm(request.POST, instance=assignment)
       if form.is_valid():
           assignment = form.save(commit=False)
           assignment.updated_date = timezone.now()
           assignment.save()
           assignments = Assignment.objects.filter(created_date__lte=timezone.now())
           return render(request, 'crm/assignment_list.html',
                         {'assignments': assignments})
   else:
        # edit
       form = AssignmentForm(instance=assignment)
   return render(request, 'crm/assignment_edit.html', {'form': form})
   
@login_required
# @user_passes_test(rolevolunteercheck)
def assignment_delete(request, pk):
   assignment = get_object_or_404(Assignment, pk=pk)
   assignment.delete()
   return redirect('crm:assignment_list')
   
@login_required
def organization_list(request):
    organization = Organization.objects.filter(created_date__lte=timezone.now())
    return render(request, 'crm/organization_list.html',
                 {'organizations': organization})

@login_required
@user_passes_test(rolemanagercheck)
def organization_new(request):
   if request.method == "POST":
       form = OrganizationForm(request.POST)
       if form.is_valid():
           organization = form.save(commit=False)
           organization.created_date = timezone.now()
           organization.save()
           organizations = Organization.objects.filter(created_date__lte=timezone.now())
           return render(request, 'crm/organization_list.html',
                         {'organizations': organizations})
   else:
       form = OrganizationForm()
       # print("Else")
   return render(request, 'crm/organization_new.html', {'form': form})

@login_required
@user_passes_test(rolemanagercheck)
def organization_edit(request, pk):
   organization = get_object_or_404(Organization, pk=pk)
   if request.method == "POST":
       # update
       form = OrganizationForm(request.POST, instance=organization)
       if form.is_valid():
           organization = form.save(commit=False)
           organization.updated_date = timezone.now()
           organization.save()
           organizations = Organization.objects.filter(created_date__lte=timezone.now())
           return render(request, 'crm/organization_list.html',
                         {'organizations': organizations})
   else:
        # edit
       form = OrganizationForm(instance=organization)
   return render(request, 'crm/organization_edit.html', {'form': form})
   
@login_required
@user_passes_test(rolemanagercheck)
def organization_delete(request, pk):
   organization = get_object_or_404(Organization, pk=pk)
   organization.delete()
   return redirect('crm:organization_list')

@login_required
# @user_passes_test(rolemanagercheck)
def volunteer_list(request):
    volunteer = Volunteer.objects.filter(created_date__lte=timezone.now())
    return render(request, 'crm/volunteer_list.html',
                 {'volunteers': volunteer})

@login_required
def volunteer_edit(request, pk):
   volunteer = get_object_or_404(Volunteer, pk=pk)
   if request.method == "POST":
       # update
       form = VolunteerForm(request.POST, instance=volunteer)
       if form.is_valid():
           volunteer = form.save(commit=False)
           volunteer.updated_date = timezone.now()
           volunteer.save()
           volunteers = Volunteer.objects.filter(created_date__lte=timezone.now())
           return render(request, 'crm/volunteer_list.html',
                         {'volunteers': volunteers})
   else:
        # edit
       form = VolunteerForm(instance=volunteer)
   return render(request, 'crm/volunteer_edit.html', {'form': form})

@login_required
def volunteer_delete(request, pk):
   volunteer = get_object_or_404(Volunteer, pk=pk)
   volunteer.delete()
   return redirect('crm:volunteer_list')

@login_required
def availability_list(request):
   availabilitys = Availability.objects.filter(created_date__lte=timezone.now())
   return render(request, 'crm/availability_list.html', {'availabilitys': availabilitys})

@login_required
# @user_passes_test(rolevolunteercheck)
def availability_new(request):
   if request.method == "POST":
       form = AvailabilityForm(request.POST)
       if form.is_valid():
           availability = form.save(commit=False)
           availability.created_date = timezone.now()
           availability.vol_name = request.user.username
           availability.save()
           availabilitys = Availability.objects.filter(created_date__lte=timezone.now())
           return render(request, 'crm/availability_list.html',
                         {'availabilitys': availabilitys})
   else:
       form = AvailabilityForm()
       # print("Else")
   return render(request, 'crm/availability_new.html', {'form': form})

@login_required
# @user_passes_test(rolevolunteercheck)
def availability_edit(request, pk):
   availability = get_object_or_404(Availability, pk=pk)
   if request.method == "POST":
       form = AvailabilityForm(request.POST, instance=availability)
       if form.is_valid():
           availability = form.save()
           # service.customer = service.id
           availability.updated_date = timezone.now()
           availability.save()
           availabilitys = Availability.objects.filter(created_date__lte=timezone.now())
           return render(request, 'crm/availability_list.html', {'availabilitys': availabilitys})
   else:
       # print("else")
       form = AvailabilityForm(instance=availability)
   return render(request, 'crm/availability_edit.html', {'form': form})

@login_required
# @user_passes_test(rolevolunteercheck)
def availability_delete(request, pk):
   availability = get_object_or_404(Availability, pk=pk)
   availability.delete()
   return redirect('crm:volunteer_list')

@login_required
def opportunity_list(request):
   opportunitys = Opportunity.objects.filter(created_date__lte=timezone.now())
   return render(request, 'crm/opportunity_list.html', {'opportunitys': opportunitys})

@login_required
@user_passes_test(rolemanagercheck)
def opportunity_new(request):
   if request.method == "POST":
       form = OpportunityForm(request.POST)
       if form.is_valid():
           opportunity = form.save(commit=False)
           opportunity.created_date = timezone.now()
           opportunity.save()
           opportunitys = Opportunity.objects.filter(created_date__lte=timezone.now())
           return render(request, 'crm/opportunity_list.html', {'opportunitys': opportunitys})
   else:
       form = OpportunityForm()
       # print("Else")
   return render(request, 'crm/opportunity_new.html', {'form': form})

@login_required
@user_passes_test(rolemanagercheck)
def opportunity_edit(request, pk):
   opportunity = get_object_or_404(Opportunity, pk=pk)
   if request.method == "POST":
       form = OpportunityForm(request.POST, instance=opportunity)
       if form.is_valid():
           opportunity = form.save()
           # service.customer = service.id
           opportunity.updated_date = timezone.now()
           opportunity.save()
           opportunitys = Opportunity.objects.filter(created_date__lte=timezone.now())
           return render(request, 'crm/opportunity_list.html', {'opportunitys': opportunitys})
   else:
       # print("else")
       form = OpportunityForm(instance=opportunity)
   return render(request, 'crm/opportunity_edit.html', {'form': form})

@login_required
@user_passes_test(rolemanagercheck)
def opportunity_delete(request, pk):
   opportunity = get_object_or_404(Opportunity, pk=pk)
   opportunity.delete()
   return redirect('crm:opportunity_list')

# @login_required
# def summary(request, pk):
    # customer = get_object_or_404(Volunteer, pk=pk)
    # customers = Volunteer.objects.filter(created_date__lte=timezone.now())
    # services = Service.objects.filter(cust_name=pk)
    # products = Product.objects.filter(cust_name=pk)
    # sum_service_charge = Service.objects.filter(cust_name=pk).aggregate(Sum('service_charge'))

crm/templates/crm/assignment_list.html
 {% extends 'crm/base.html' %}
 {% block content %}

    <html>
    <head>
        <meta charset="UTF-8">
        <title>Volunteer Management Services</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    </head>
    <body>
    <style>
        body {
            background-color: white;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        Volunteer Management Services, Help the Community You Love!.
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Assignment Information</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Volunteer Name</th>
                <th>Opportunity</th>

                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for assignment in assignments %}
                <tr>
                    <td>{{ assignment.volunteer }}</td>
                    <td>{{ assignment.opportunity }}</td>

                    <td><a href="{% url 'crm:assignment_edit' pk=assignment.pk %}" class="btn btn-warning">Edit</a>

<td><a href="{% url 'crm:assignment_delete' pk=assignment.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>
                    </td>

                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
	<div class="row">
         <a href="{% url 'crm:assignment_new' %}" class="row"><span
                    class="btn btn-primary">Add Assignment</span></a>
    </div>
    </body>
    </html>
{% endblock %}

crm/templates/crm/availability_delete.html
 {% extends 'crm/base.html' %}
 {% block body_block %}
    <h1>Delete {{ availability.name }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'crm:home' pk=availability.vol_number %} ">Cancel</a>

    </form>

{% endblock %}

crm/templates/crm/availability_list.html
{% extends 'crm/base.html' %}
{% block content %}
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Volunteer Management Systems</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    </head>
    <body>
    <style>
        body {
            background-color: white;
        }
        a {

            width:100%
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        Volunteer Management Services, Help the Community You Love!.
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Availability Information</h2>
    </div>
    <div>
        <table id="a" class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Volunteer Name</th>
                <th>Category</th>
                <th width="100%">Description</th>
                <th>Location</th>
                <th>Arrive Time</th>
                <th>Leave Time</th>
                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for availability in availabilitys %}
                <tr>
                    <td>{{ availability.vol_name }}</td>
                    <td>{{ availability.service_category }}</td>
                     <td>{{ availability.description }}</td>
                    <td>{{ availability.location }}</td>
                    <td>{{ availability.setup_time }}</td>
                    <td>{{ availability.cleanup_time }}</td>
                    <td><a href="{% url 'crm:availability_edit' pk=availability.pk %}"
                           class="btn btn-warning">Edit</a></td>
                    <td><a href="{% url 'crm:availability_delete' pk=availability.pk %}"

                           class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    <div class="row">
         <a href="{% url 'crm:availability_new' %}" class="row"><span
                    class="btn btn-primary">Add Availability</span></a>
     </div>
    </div>
    </body>
    </html>
{% endblock %}

crm/templates/crm/base.html
{% load staticfiles %}

<html lang="en">
<head>
    <title>Volunteer Management Services</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
        }

        /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
        .row.content {
            height: 450px
        }

        /* Set gray background color and 100% height */
        .sidenav {
            padding-top: 20px;
            background-color: #f1f1f1;
            height: 100%;
        }

        /* Set black background color, white text and some padding */
        footer {
            background-color: #555;
            color: white;
            padding: 15px;
        }

        /* On small screens, set height to 'auto' for sidenav and grid */
        @media screen and (max-width: 767px) {
            .sidenav {
                height: auto;
                padding: 15px;
            }

            .row.content {
                height: auto;
            }
        }
    </style>
</head>
<body id="app-layout">
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#myNavbar">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Branding Image -->
            <a class="navbar-brand" href="/">
                Volunteer Management Services
            </a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'crm:home' %}">Home</a></li>
                <li><a href="{% url 'crm:volunteer_list' %}">Volunteers</a></li>
               <li><a href="{% url 'crm:availability_list' %}">Availabilities</a></li>
                <li><a href="{% url 'crm:opportunity_list' %}">Opportunities</a></li>
				<li><a href="{% url 'crm:assignment_list' %}">Assignments</a></li>
				<li><a href="{% url 'crm:organization_list' %}">Organizations</a></li>

            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'logout' %}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="content container">
    <div class="row">
        <div class="col-md-8">
            {% block content %}
                <div class="links">
                    <!-- Example row of columns -->
                    <div class="row">
                        <div class="col-md-3">
                            <div class="thumbnail">
                                <img src="{% static "images/customer.jpg" %}" alt="customer"/>
                                <div class="caption">
                                    <h2>Volunteers</h2>
                                    <p>We see our success in our volunteers success.</p>
                                    {% if user.is_authenticated %}
                                        <p><a class="btn btn-default" href="{% url 'crm:volunteer_list' %}"
                                              role="button">View
                                            details &raquo;</a></p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="thumbnail">
                                <img src="{% static "images/cupcakes.jpeg" %}" alt="cupcakes"/>
                                <div class="caption">
                                    <h2>Opportunities</h2>
                                    <p>Find an Opportunity to Volunteer and Help your Community.</p>
                                    <p><a class="btn btn-default" href="{% url 'crm:opportunity_list' %}"
                                           role="button">View
                                        details &raquo;</a></p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="thumbnail">
                                <img src="{% static "images/lunch.jpeg" %}" alt="lunch"/>
                                <div class="caption">
                                    <h2>Availabilities</h2>
                                    <p>Tell us when you are available with your time and talents.</p>
                                    <p><a class="btn btn-default" href="{% url 'crm:availability_list' %}" role="button">View
                                        details &raquo;</a></p>
                                </div>
                            </div>
                        </div>
						<div class="col-md-3">
                            <div class="thumbnail">
                                <img src="{% static "images/lunch.jpeg" %}" alt="lunch"/>
                                <div class="caption">
                                    <h2>Assignments</h2>
                                    <p>Check out where and when you are volunteering.</p>
                                    <p><a class="btn btn-default" href="{% url 'crm:assignment_list' %}" role="button">View
                                        details &raquo;</a></p>
                                </div>
                            </div>
                        </div>
						<div class="col-md-3">
                            <div class="thumbnail">
                                <img src="{% static "images/lunch.jpeg" %}" alt="lunch"/>
                                <div class="caption">
                                    <h2>Organizations</h2>
                                    <p>A new way to find great local nonprofits.</p>
                                    <p><a class="btn btn-default" href="{% url 'crm:organization_list' %}" role="button">View
                                        details &raquo;</a></p>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            {% endblock %}
        </div>
    </div>
</body>
</html>

crm/templates/crm/opportunity_list.html
 {% extends 'crm/base.html' %}
 {% block content %}
    <body>
    <style>
        body {
            background-color: white;
        }
        a {

            width:100%
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        Volunteer Management Services, Help the Community You Love!
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Opportunity Information</h2>
    </div>
    <div>
        <table id="a" class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Organization</th>
                <th>Date</th>
                <th>Time</th>

            </tr>
            </thead>
            <tbody>
            {% for opportunity in opportunitys %}
                <tr>
                    <td>{{ opportunity.organization }}</td>
                    <td>{{ opportunity.date }}</td>
                    <td>{{ opportunity.time }}</td>

                    <td><a href="{% url 'crm:opportunity_edit' pk=opportunity.pk %}"
                           class="btn btn-warning">Edit</a></td>
                    <td><a href="{% url 'crm:opportunity_delete' pk=opportunity.pk %}"

                           class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    <div class="row">
         <a href="{% url 'crm:opportunity_new' %}" class="row"><span
                    class="btn btn-primary">Add Opportunity</span></a>
    </div>
    </div>
    </body>
    </html>
{% endblock %}

crm/templates/crm/organization_delete.html
 {% extends 'crm/base.html' %}
 {% block body_block %}
    <h1>Delete {{ organization.name }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'crm:home' pk=organization.vol_number %} ">Cancel</a>

    </form>

{% endblock %}

crm/templates/crm/organization_list.html
 {% extends 'crm/base.html' %}
 {% block content %}
    <body>
    <style>
        body {
            background-color: white;
        }
        a {

            width:100%
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        Volunteer Management Services, Help the Community You Love!
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Organization Information</h2>
    </div>
    <div>
        <table id="a" class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Name</th>
                <th>Street</th>
                <th>City</th>
                <th>State</th>
                <th>Zip</th>
                <th>Phone</th>
            </tr>
            </thead>
            <tbody>
            {% for organization in organizations %}
                <tr>
                    <td>{{ organization.name }}</td>
                    <td>{{ organization.street }}</td>
                    <td>{{ organization.city }}</td>
                    <td>{{ organization.state }}</td>
                    <td>{{ organization.zip }}</td>
					<td>{{ organization.phone }}</td>
                    <td><a href="{% url 'crm:organization_edit' pk=organization.pk %}"
                           class="btn btn-warning">Edit</a></td>
                    <td><a href="{% url 'crm:organization_delete' pk=organization.pk %}"

                           class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    <div class="row">
         <a href="{% url 'crm:organization_new' %}" class="row"><span
                    class="btn btn-primary">Add Organization</span></a>
    </div>
    </div>
    </body>
    </html>
{% endblock %}